[package]
name = "server"
version = "0.1.0"
edition = "2024"
default-run = "server"

[dependencies]
actix-cors = "0.7.1"
actix-web = "4.11.0"
argon2 = "0.5.3"
futures-util = "0.3.31"
jsonwebtoken = "9.3.0"
password-hash = { version = "0.5.0" }
rand = "0.8.5"
refinery = { version = "0.8.16", features = ["tokio-postgres"] }
serde = "1.0.228"
tokio = { version = "1.47.1", features = ["full"] }
tokio-postgres = "0.7.14"
